apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-elasticsearch-pv00
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-0
    namespace: monitoring
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1684931662990-8081-pd.csi.storage.gke.io    
    volumeHandle: projects/f5-gcs-4261-sales-sa-all/zones/us-central1-c/disks/pvc-bda4d0c1-69f9-48bd-aa03-aadf477553f0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-central1-c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-elasticsearch-pv01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-1
    namespace: monitoring
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1684931662990-8081-pd.csi.storage.gke.io        
    volumeHandle: projects/f5-gcs-4261-sales-sa-all/zones/us-central1-c/disks/pvc-bda4d0c1-69f9-48bd-aa03-aadf477553f0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-central1-c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-elasticsearch-pv02
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-2
    namespace: monitoring
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1684931662990-8081-pd.csi.storage.gke.io
    volumeHandle: projects/f5-gcs-4261-sales-sa-all/zones/us-central1-c/disks/pvc-bda4d0c1-69f9-48bd-aa03-aadf477553f0        
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-central1-c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  volumeMode: Filesystem