apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"