apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-elasticsearch-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  hostPath:
    path: /mnt/data