apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: monitoring
spec:
  ports:
  - name: "25826"
    protocol: TCP
    port: 25826
    targetPort: 25826
  - name: "5044"
    protocol: TCP
    port: 5044
    targetPort: 5044
  - name: "5261"
    protocol: TCP
    port: 5261
    targetPort: 5261
  - name: "5561"
    protocol: UDP
    port: 5561
    targetPort: 5561    
  selector:
    app: logstash